# Generated by Django 5.1.2 on 2024-11-01 16:18

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='слаг')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Владелец категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('slug', models.SlugField(verbose_name='слаг')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание c html')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='видео')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='post.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('-date_added',),
            },
        ),
    ]
