# Generated by Django 4.2.16 on 2024-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
