# Generated by Django 4.2.16 on 2024-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Статус'),
        ),
    ]
